# Generated by Django 5.2 on 2025-04-23 22:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveSmallIntegerField()),
                ('kilometraje_actual', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('GEN', 'Genérico'), ('ACE', 'Cambio de aceite')], default='GEN', max_length=3)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('kilometraje_registrado', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('costo_partes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='CambioAceite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateField()),
                ('km_cambio', models.PositiveIntegerField()),
                ('intervalo_km', models.PositiveIntegerField(default=5000)),
                ('intervalo_meses', models.PositiveSmallIntegerField(default=3)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo')),
            ],
        ),
    ]
