# Generated by Django 5.2 on 2025-05-01 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_trabajo_costo_mano_obra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimadoReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEstimado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('costo_partes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.estimadoreparacion')),
            ],
        ),
    ]
